<a href="https://colab.research.google.com/github/widawek/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3])
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim # wymiar tablicy

1

In [ ]:
x.shape # liczba wymiarów

(2,)

In [ ]:
x.size # liczba komórek

2

In [ ]:
x.dtype # typ danych w tablicy 

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


2D Array

In [4]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1,2,4], [2,3,4]])
print(x)

[[1 2 4]
 [2 3 4]]


In [ ]:
x.shape   # vertical, horizontal (rows, columns)

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1],
     [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

TYPY DANYCH

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1, 2, 3], dtype="float")
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype="complex")
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.0, 2.3, 3.3], dtype="int")
A.dtype
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([23, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([23, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

TWORZENIE TABLIC

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype="int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=20)

array([10, 30, 50, 70, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
for i in np.arange(0, 1, 0.1):
  print(round(i,1))

In [ ]:
np.linspace(start=0.1, stop=1, num=10)   # rozkłada podaną ilość elementów w równych odstępach w danym przedziale

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3)) # za pomocą -1 dobieramy ilość parametró w danym wymiarze "do końca"

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

PODSTAWOWE OPERACJE NA TABLICACH

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B  # można wykonywac takie działania jezeli rozmiar tablicy się pokrywa

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A + 2 * B

array([ 9, -1, 10,  6])

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, "\n")
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X * Y # mnożenie po elemencie

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y) # mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)  # mnożenie macierzowe nie jest przemienne

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y  # kolejny sposób mnozenia macierzowego (symbol add)

array([[  3,   6],
       [-12,   0]])

GENEROWANIE LICZB LOSOWYCH

In [5]:
np.random.seed(0)

In [6]:
np.random.randn() # losowa wartość z rozkładu normalnego

1.764052345967664

In [7]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [ ]:
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10)

3

In [ ]:
np.random.randint(low=10, high=101)

56

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [ ]:
np.random.choice([4, 2, 1, 2])

1

In [ ]:
np.random.choice(["python", "Java", 1, 2])

'1'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)  # w bibliotece numpy w odróżnieniu od pandas nie musimy przypisywac nowej zmiennej (jest ona podmieniona automatycznie)

In [ ]:
data

array([9, 6, 1, 2, 8, 7, 5, 3, 4, 0])

PODSTAWOWE FUNKCJE

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9) # wynik zawsze float

3.0

In [ ]:
np.all([2, 3, 1])  # jeżeli kazda wartość zrwaca prawde wtedy funkcja all zwraca True

True

In [ ]:
np.any([0, 0, 0]) # jeżeli którakolwiek wartość zwraca True wtedy any zwraca True

False

In [ ]:
A = np.random.rand(5)
A

array([0.50132438, 0.95608363, 0.6439902 , 0.42385505, 0.60639321])

In [ ]:
np.argmax(A)

1

In [ ]:
A[np.argmax(A)] # wydobywanie maksymalnej wartość z tablicy

0.9560836347232239

In [ ]:
A[np.argmin(A)]

0.4238550485581797

In [ ]:
np.argsort(A) # sortowanie indeksami

array([3, 0, 4, 2, 1])

In [ ]:
np.max(A)

0.9560836347232239

In [ ]:
np.min(A)

0.4238550485581797

In [ ]:
np.mean(A)

0.6263292957131336

In [ ]:
np.median(A)

0.6063932141279244

In [ ]:
np.std(A)

0.18224671639823387

INDEKSOWANIE, WYCINANIE

In [8]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [10]:
A[2]

2

In [11]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [12]:
A[[0, 5, 6]]  # wycinanie po indeksach elementów

array([0, 5, 6])

In [13]:
A[-1]

19

In [14]:
A[10:-2]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [15]:
A = A.reshape(4, 5) # ta metoda nie podmienia zmiennej...
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [17]:
A[1, 2] = 14  # przypisanie nowej wartosci

In [18]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

ITERACJA PO TABLICACH

In [22]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat:
  print(item)

ZMIANA ROZMIARU TABLIC

In [27]:
A.shape

(4, 5)

In [28]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
A.ravel() # wypłaszczenie danych w tablicy kolejno po wierszach

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
A.T   # transpozycja (wiersz na kolumne kolumna na wiersz)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

MASKI LOGICZNE

In [33]:
C = np.arange(-10, 10, step=0.5)
C.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [40]:
C[C > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [42]:
C[np.bitwise_and(C > -5, C < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [44]:
np.bitwise_or(C < -5, C > 5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])