<a href="https://colab.research.google.com/github/widawek/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.6'

Norma wektorowa, długość wektora w R2



In [ ]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)  # normalizacja (dlugosc) wektora

4.123105625617661

Norma Euklidesowa

In [ ]:
v2= np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów w płaszczyźnie

In [ ]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p - q)

5.0

Odległość dwóch punktów w przestrzeni Rn (n wymiarów)

In [ ]:
p = np.array([3,0, 1])
q = np.array([0,4, 2])
np.linalg.norm(p - q)

5.0990195135927845

MNOŻENIE MACIERZY


Aby móc pomnożyć dwie macierze liczba kolumn w lewej macierzy musi zgadzać się z liczba wierszy w prawej macierzy.

Mnożenie macierzy nie jest przemienne.

In [ ]:
X = np.array ([[5, 3], [3, 9]])
Y = np.array ([[1], [-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, "\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
Z = np.dot(X,Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [ ]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

WYZNACZNIK MACIERZY

In [4]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

In [5]:
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

In [6]:
np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [10]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [14]:
np.set_printoptions(precision=4, suppress= True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [17]:
A.T # transpozycje

array([[ 2, -1],
       [ 4,  3]])

In [19]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [20]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [21]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])